nodeLinker: pnp

packageExtensions:
  eslint-plugin-prettier@*:
    dependencies:
      eslint-config-prettier: "*"
  mocha@*:
    dependencies:
      ts-node: "*"
  swagger-express-ts@*:
    dependencies:
      lodash: "*"
      reflect-metadata: "*"
  typeorm-store@*:
    dependencies:
      express-session: "*"
  typeorm@*:
    dependencies:
      mysql2: "*"
      sqlite3: "*"

yarnPath: .yarn/releases/yarn-3.6.4.cjs
