export enum RouterParam {
  REQUEST = "request",
  RESPONSE = "response",
  NEXT = "next",
  BODY = "body",
  QUERY = "query",
  PARAMETERS = "params",
  HEADERS = "headers",
  SESSION = "session",
  FILE = "file",
  FILES = "files",
  HOST = "host",
  IP = "ip",
  USER = "user",
}
